# -*- coding: utf-8 -*-
"""Order food.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18vqc3OIeYt1bGrAcxPBKlByM0XnBtYQB
"""

print("Menu : H=Hamburger, P=Pizza, W=Water, E=Exit")
menu = input("Choose menu(H,P,W,E=exit) : ").upper()
total = 0
while menu != "E" :
  amt = int(input("Enter amount : "))
  if menu == "H" :
    total = total + (amt*90)
  elif menu == "P" :
    total = total + (amt*185)
  elif menu == "W" :
    total = total + (amt*20)
  print()
  print("Menu : H=Hamburger, P=Pizza, W=Water, E=Exit")
  menu = input("Choose menu(H,P,W,E=Exit) : ").upper()
print("Total price = %0.2f Baht"%(total))